module Nmbrs
  class EmployeeService
    def initialize(configuration)
      @configuration = configuration

      @client = Savon.client(
        wsdl: Nmbrs::WSDLS[:employee_service],
        # convert_request_keys_to: :camelcase,
        # TODO REMOVE SSL_VERIFY_MODE IN PRODUCTION!
        # ssl_verify_mode: :none,
        env_namespace: :soapenv,
        namespace_identifier: :com,
        soap_header: { 'com:AuthHeader' => { 'com:Username' => configuration.username, 'com:Token' => configuration.api_key }  }
      )
    end

    def request(action, data = {})
      @client.call(action, message: data)
    end
  end
end

# [:wage_tax_update,
#  :wage_tax_get_current,
#  :wage_tax_get_list,
#  :wage_tax_get,
#  :cost_center_update_current,
#  :cost_center_update,
#  :cost_center_get_current,
#  :cost_center_get,
#  :function_update_current,
#  :function_get_current,
#  :function_get_all_all_employees_by_company,
#  :function_get_all_all_employees_by_company_v2,
#  :department_update_current,
#  :department_get_current,
#  :department_get_all_all_employees_by_company,
#  :lease_car_insert,
#  :lease_car_get_current,
#  :lease_car_get,
#  :lease_car_get_list,
#  :lease_car_delete,
#  :lease_car_stop,
#  :days_var_get,
#  :days_var_get_current,
#  :days_var_set_current,
#  :days_var_set,
#  :hour_component_var_get,
#  :hour_component_var_get_current,
#  :hour_component_var_clear_current,
#  :hour_component_var_clear,
#  :hour_component_var_insert_current,
#  :hour_component_var_insert,
#  :hour_component_var_insert_batch,
#  :hour_component_delete,
#  :wage_component_var_get,
#  :wage_component_var_get_current,
#  :wage_component_var_clear_current,
#  :wage_component_var_clear,
#  :wage_component_var_insert_current,
#  :wage_component_var_insert,
#  :wage_component_var_insert_batch,
#  :wage_component_delete,
#  :personal_info_get_current,
#  :personal_info_get,
#  :personal_info_update_current,
#  :personal_info_update,
#  :personal_info_get_all_all_employees_by_company,
#  :list_get_by_company,
#  :list_get_by_debtor,
#  :employee_get_current,
#  :employee_insert,
#  :employee_insert_based_on_default,
#  :children_get,
#  :child_delete,
#  :children_update,
#  :children_insert,
#  :children_insert_batch,
#  :partner_update,
#  :partner_delete,
#  :partner_get,
#  :reports_get_journals_report_by_employee,
#  :employment_get_all_all_employees_by_company,
#  :employee_document_upload_document,
#  :hour_component_fixed_get,
#  :hour_component_fixed_get_current,
#  :hour_component_fixed_insert_current,
#  :hour_component_fixed_insert,
#  :hour_component_fixed_insert_batch,
#  :hour_component_fixed_stop,
#  :address_insert_current,
#  :address_get_list_current,
#  :address_get_list,
#  :address_get_all_all_employees_by_company,
#  :address_delete,
#  :address_update,
#  :bank_account_insert_current,
#  :bank_account_get_list_current,
#  :bank_account_get_list,
#  :bank_account_delete_current,
#  :contract_delete,
#  :contract_insert_v2,
#  :contract_insert_current_period_v2,
#  :contract_get_all_v2,
#  :contract_get_all_all_employees_by_company,
#  :contract_get_current_period,
#  :absence_insert,
#  :absence_get_list,
#  :leave_insert,
#  :leave_get_list,
#  :leave_balance_get,
#  :levensloop_insert,
#  :levensloop_stop,
#  :levensloop_delete,
#  :levensloop_get,
#  :spaarloon_insert,
#  :spaarloon_stop,
#  :spaarloon_get,
#  :spaarloon_delete,
#  :spaarloon_get_list,
#  :service_get_list,
#  :service_stop_current,
#  :service_insert,
#  :service_insert2,
#  :days_fixed_get,
#  :days_fixed_get_current,
#  :days_fixed_set_current,
#  :days_fixed_set,
#  :days_fixed_stop,
#  :wage_component_fixed_get,
#  :wage_component_fixed_get_current,
#  :wage_component_fixed_insert_batch,
#  :wage_component_fixed_insert_batch_with_end,
#  :wage_component_fixed_insert,
#  :wage_component_fixed_insert_with_end,
#  :wage_component_fixed_insert_current,
#  :wage_component_fixed_insert_current_with_end,
#  :wage_component_fixed_stop,
#  :schedule_update_current,
#  :schedule_update,
#  :schedule_get_current,
#  :schedule_get,
#  :schedule_get_list,
#  :schedule_get_all_all_employees_by_company,
#  :salary_update_current,
#  :salary_update,
#  :salary_get_current,
#  :salary_get,
#  :salary_get_list,
#  :salary_get_all_all_employees_by_company,
#  :svw_update_current,
#  :svw_update,
#  :svw_get_current,
#  :svw_get,
#  :svw_get_list,
#  :svw_get_all_all_employees_by_company,
#  :wage_tax_update_current]
